name: Pre-Release

on:
  workflow_dispatch:
    inputs:
      prerelease_version:
        description: 'Pre-release type'
        required: true
        default: 'prerelease'
        type: choice
        options: ['prepatch', 'preminor', 'premajor', 'prerelease']
      packages:
        description: 'Package directory to release'
        required: true
        default: 'electron'
        type: choice
        options:
          - core
          - electron
          - middleware
          - tauri
          - tauri-plugin
          - types
      dry_run:
        description: 'Dry run - no changes made'
        required: false
        default: false
        type: boolean

jobs:
  pre-release:
    name: Pre-release
    uses: ./.github/workflows/_release-publish.reusable.yml
    with:
      release_version: ${{ inputs.prerelease_version }}
      packages: ${{ inputs.packages }}
      dry_run: ${{ inputs.dry_run }}
    secrets:
      GITHUB_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_API: ${{ secrets.TURBO_API }}
